### ISSUE TITLE
GitHub pages website instead of rjno1?

### ISSUE THREAD

**Issue by vwvtkxjobkvpqszygxmjvgaavwvfju** [422658476/MPV-EASY-Player#1]
The rjno1 page is inaccessible to me. "禁用广告屏蔽(ad blocker)，刷新页面继续浏览 / Please disable your ad blocker!"

Maybe it is a good idea to use [GitHub pages](https://pages.github.com/)?

**Comment by 422658476** [comment]
The server needs advertising support to run, but adblocker has been constantly enhancing its rules to block ads. My attitude towards adblocker is: as a thief, stole my home, I have posted a note on the door. Tell you not to sneak into my house, it is still invisible to steal the door of my house, since the police can not catch, then I desperately locked it until it can not open.
The disadvantage of locking is that it will be accidentally injured. If you encounter this, if you open the adblock, close it and refresh the page. If you don't open it, you can solve it by refreshing the page.
The official website of the software and github do not need to be replaced, because when the new version is released, the official website and github are updated synchronously. If you have problems with the official website, you can download the software directly by visiting github and you can see the update log.

**Comment by 422658476** [comment]
I spend more time on the web than I can make this software. I have the ability to maintain the server, the server operating system, all parts of the web page, I don't need github, because I have the ability to do everything I need, And I am proud of it.
