### ISSUE TITLE
Playback History

### ISSUE THREAD

**Issue by smaragdus** [422658476/MPV-EASY-Player#2]
Although **save playback position and history** is checked **open recently played file**  drop-down menu is empty (showing only 5 asterisks (*) plus **refresh** button. However playback position is saved correctly.

**MPV-EASY Player** version [0.29.0.0](https://github.com/422658476/MPV-EASY-Player/releases/tag/0.29.0.0), x64, Windows 8 x64.

**Comment by 422658476** [comment]
Thank you very much for your feedback.

But I don't have a win 8 system, so I have tested it on Windows 7, Windows 10, and Windows 7 English, but I can't reproduce this problem.

And I also think this issue is not related to the operating system version.

Can you help with these more tests:
1. Open 5 files (open one at a time) by double-clicking the video file to see if the playback history is still *
2. If you have more than one computer, can you perform these similar operations on more computers, check whether the playback history on each computer is still *, I want to determine the reason through different environments.
3, when you play a few files, and the play history is *, please help check if there is a play history file under mpv-easy player\data\mpv-easy-data\watch_later.
These are very welcome to add some screenshots to make it easier to troubleshoot.

At least until now, through your feedback, I found that in mpv-easy borderless gui mode, playing files using drag and drop, the playback history will not be generated normally, thank you very much.

**Comment by smaragdus** [comment]
@422658476 

Hello there,

**MPV-EASY Player** is not associated with video files so I cannot double click video files to play them.

I added files via "drag&drop" and via "open file..." dialog, it was all the same, the "open recently played file" menu was empty, screen:

![mpv-easy player 0 29 0 0 - 2018-07-26 - 001](https://user-images.githubusercontent.com/9025757/43231601-bc33ce60-9075-11e8-9df6-467d26a3631f.png)

another screen showing that the player has loaded a video file:

![mpv-easy player 0 29 0 0 - 2018-07-26 - 002](https://user-images.githubusercontent.com/9025757/43231615-cf194f0a-9075-11e8-808b-906bca5db8b9.png)

I have another old machine but it is Windows XP system and it is not where I live now.

Yes, there are 9 files in "watch_later" sub-folder.

I am glad that the player is fully portable but I have had two more issues:

- **MPV-EASY Player** is always "on top", I disable "on top" exit it and when I restart it it is "on top" again. When I open **rjno1.conf** and manually change "ontop=yes" to "ontop=no" when I restart it **MPV-EASY Player** is on top again. Can you confirm that?
- When I minimize **MPV-EASY Player** playback is automatically paused- I want to disable this but I do not know how- sometimes when I play music video I want it playing in the background (minimized) but this doesn't seem possible. Or perhaps I am missing some setting?

Currently I am using **MPV-EASY Player** with **MPV-EASY Borderless GUI** and **mode 1**.

If needed I can pack **data** sub-folder with all its settings into an archive and upload it.

If I can help further with the investigation of file history problem please let me know.

**Comment by 422658476** [comment]
Thanks a lot, the reason for dragging and dropping the file playlist to the * is already found.
The problem you said is invalid. This is because the current two functions in the default gui have no optional parameters and will not be changed as the settings in the configuration file change.
In the next version I will associate these 2 functions with the corresponding options in the settings.
