### ISSUE TITLE
Multilanguage issues

### ISSUE THREAD

**Issue by bovirus** [422658476/MPV-EASY-Player#27]
@422658476 

I have some request aboout multilanguage

**_Language file to translate_**

Is it nececssary to translate this file

https://github.com/422658476/MPV-EASY-Player/blob/master/mpv-easy-data/lang/en-us.ini

in other language (like Italian)?

**_NSIS installer_**

Could be possible to localize these strings (please see red boxes)

![image](https://user-images.githubusercontent.com/1262554/133405238-fc30e844-fd22-41ff-b1b9-57999790a392.png)

![image](https://user-images.githubusercontent.com/1262554/133406254-5d3b8c0d-42fd-4b75-b751-5b9d33793335.png)

![image](https://user-images.githubusercontent.com/1262554/133406290-d07da359-e295-4e2b-bb2d-8054a1ea401f.png)

File properteis

Could be possible not use japanese charcaters?

Could be possible to update the version reported as 2.6.0.0 with MPV Easy Player version?

![image](https://user-images.githubusercontent.com/1262554/133406575-8d4bdf28-34b8-4320-9ab4-ac4331547bf6.png)

**Comment by 422658476** [comment]
Thank you very much, but this program is just for simplicity and stability. It only provides English and Chinese interfaces without translation.
Most procedures are similar, and everyone knows how to operate.
Many thanks.
i will close this。👌

**Comment by bovirus** [comment]
@422658476

Please don't close teh tocket oif all issues are clsoed.

I doidn't udnerstand why only English and chinese.
The instalelr is created with NSIS.
If you add the strings for english and chinese why don't add strings for italian?
It's very simpole job and I can help you about it

And what about file properties chinese characters?

And what about english files?
Is it necessary to translate?

**Comment by 422658476** [comment]
Because the test of changing the interface language needs to judge the language of the operating system.
Now the logic of the display language of the nsis interface is automatically judged and automatically switched by obtaining which language the interface of the operating system uses. I don't want the interface language selection interface to appear.
If I want to test the English interface, then I need an English operating system, if I want to test the Italian interface, then I need an Italian operating system, or I may need to install Italian on the English operating system and then test.
This process takes too much debugging time for a program that is only used for decompression, and it is too prone to additional errors.
I don’t want this program to show the wrong interface language.
So as long as it is not a Chinese operating system, the most common English interface will be used.
In this way, you can operate even if you don't understand it. The three interfaces are to select the version, select the decompression path, and decompress. This is very easy to understand, because most programs have similar interfaces.

**Comment by bovirus** [comment]
@422658476 

I knwo very well it because I developped many script for NSIS.

In NSIS iyou enable auto detect language and italian langauge strings are availble it use Italian strings ina  Italian OS.

For me the scope of translator is not only translate.
But also to help you to test the program in context that you cannmot test (ex. in Windows with Italian language).
If you pass me the list of strings that you use in your installer I can tarnslate and you can craete a etst version.
Then I will able to etst in my Italian system and provdie all feedback to you.

It's the same job that I did for your GUI.

**Comment by 422658476** [comment]
This is where the problem lies. Multi-language testing relies too much on other people and operating systems that I don’t have. It will take a lot of time to communicate and update the code, and of course bug debugging.
This is a program that does not require additional translation, it is already sufficient, and there is no need to spend additional time debugging, updating and translating it.
In fact, it is a better way to create a similar program that only needs icons and pictures to understand the interface functions, but I don't know how to create it, because this requires studying nsis related plug-ins and codes. 
thank you very much 。

**Comment by bovirus** [comment]
@422658476 

As I explained I'm here to help and support to test it in Italian OS.
You don't care about this job because it's in charge of myself.

If you send me your nsis script I can check how can add italian language.

In this case don't need so debug because youd didn't change the code but only strings.

Thanks.

**Comment by 422658476** [comment]
Let me first try to make a version that can be installed smoothly without translation, just by looking at the interface picture, which completely solves the problem of interface translation.

**Comment by 422658476** [comment]
I have redesigned an interface, the function is basically complete, no translation is needed, it will be enabled in the next version
![1](https://user-images.githubusercontent.com/37802190/133759475-0a6ba2f2-0b95-48e5-8d17-249e050995c5.png)
![2](https://user-images.githubusercontent.com/37802190/133759487-34e46205-d9dd-4f39-8d3f-f8c413022874.png)

**Comment by 422658476** [comment]
The multi-language support has fully met expectations. The functions and bugs have been tested and there are no problems. I will close this issue. thank you very much.

**Comment by bovirus** [comment]
@422658476 

Please provide me if you can a link to test new instalelr it in Italian OS.
Thanks.

**Comment by 422658476** [comment]
In order to control the size, the complete player file is not included 
[MPV-EASY Player V0.33.0.14 test-zip.zip](https://github.com/422658476/MPV-EASY-Player/files/7188026/MPV-EASY.Player.V0.33.0.14.test-zip.zip)

**Comment by bovirus** [comment]
Thanks.
It works

![image](https://user-images.githubusercontent.com/1262554/133878288-b10731de-5b03-4a96-abc2-3fc19f71eaf9.png)

![image](https://user-images.githubusercontent.com/1262554/133878297-71709212-2bf5-4107-bd16-9c0019b8621a.png)

**_- Proposals_** 

**_Default installation folder_**

MPV-EASY Player 0.33.0.14 32bit - for 32bit version (now is MPV-EASY Player V0.33.0.14)
MPV-EASY Player 0.33.0.14 64bit - for 64bit version (now is MPV-EASY Player V0.33.0.14)

**_- Main window - title on top left_**

Now is **_MPV-EASY layer.zip_**
I propose **_MPV-EASY layer_**

**- Button ?**

I dind't udneratand the meaning of "?" white on blue background.

**Comment by 422658476** [comment]
This is the latest version:

I have found the perfect way to make the text below support multiple languages without additional translation
【Free space availble:】
【Program space:】

The default installation folder does not need to add 32bit or 64bit.
Some people need 32bit or 64bit, some people don't.
You can add it manually if necessary.
If the default is 32bit or 64bit, you don't need to delete these characters manually.
The operations are similar, one is to delete and the other is to add.

MPV-EASY Player-zip will not be changed to MPV-EASY Player. Because it needs to remind users that this is not a player ,it is a self-extracting program for compressed files.

The question mark has been made easier to understand through the newly designed picture. 

[MPV-EASY Player V0.33.0.14-test-zip.zip](https://github.com/422658476/MPV-EASY-Player/files/7189533/MPV-EASY.Player.V0.33.0.14-test-zip.zip)

**Comment by bovirus** [comment]
@422658476 

Thanks for new version.

I believe that the graphic with ? ? can create misndersnading and not add relevant info.
For me you can remove it without limitations.

Pelase make this changes

Spazio libero -> spazio libero
Spazio necessario -> spazio necessario

because are not starting string and not require capital letter.

Aboyt .zip I beleiev that can replace with

MPV-EASY player-zip -> MPV-EASY Player - Unpacker (english)
MPV-EASY player-zip -> MPV-EASY Player - Decompressione (italian)

because also here you create misudnerstanding because file is .exe and you mentioned .zip.

![image](https://user-images.githubusercontent.com/1262554/133883941-461a8aa1-984c-405b-8293-dd1f064e0a72.png)

My proosal for graphics layout

Disco (ita) = Disk
Cartalla (ita) = Folder

**Comment by 422658476** [comment]
The deepened rounded rectangle on the picture also contains the meaning of the steps.
This is why the deepened rounded rectangles are on the left, middle, and right sides, respectively, which represent the first step, the second step, and the third step.
So the second picture will not be deleted, I believe most people also understand the meaning of the picture.
[Free space availble:] The Italian translation of [Program space:] will not be modified, because this calls the standard translation that comes with nsis and does not need to be modified.

-zip
This cannot be translated. It is displayed as -zip in all languages, which is why it is not Unpacker or Decompressione. No matter what language the user uses, the meaning of -zip can be understood.

Thanks a lot for debugging and comments. I will close this issue again. The improvement of the new interface is over.

**Comment by bovirus** [comment]
@422658476 

My idea that the "?" can create only doubts/misunderstanding and not add significative help.

And then logo of MPV:-EASY player graphic should be on the left and 32/64 graphic on the right because on the left is more visbile.

**Comment by 422658476** [comment]
Below is the last version, which has been optimized enough that no more changes will be made.
Thank you so much for the feedback. 
[MPV-EASY Player V0.33.0.14-test.zip](https://github.com/422658476/MPV-EASY-Player/files/7191182/MPV-EASY.Player.V0.33.0.14-test.zip)
