### ISSUE TITLE
Purge github repository file/folders - Not use chinese charcters for files

### ISSUE THREAD

**Issue by bovirus** [422658476/MPV-EASY-Player#28]
@422658476 

What do you think about cleanup of folders/files in github if are not necessary?
Or to not use chinese characters in file names 

Please check here 

https://github.com/422658476/MPV-EASY-Player/tree/master/mpv-easy-data
for "old-version-xxxxxx" folders?

https://github.com/422658476/MPV-EASY-Player/tree/master/portable-data/scripts
old-version-xxxxxxx folders?

https://github.com/422658476/MPV-EASY-Player/tree/master/mpv-easy-data/osc-style
old-version-xxxxxxxx folders?

https://github.com/422658476/MPV-EASY-Player/tree/master/tutorial
修改后的osc.lua file?

Thanks.

**Comment by 422658476** [comment]
The use of Chinese file names was the initial behavior, and there will be no Chinese file names in the future.
The old version of the folder is necessary for me, because some changes will cause some files to disappear. If some people need these old files, they won’t be able to find them.
For example, other.js was used in the old version, and other.lua is now used.
Because of the mpv bug, if there is a js script, the non-native gui will fail to open, and the lua script can only be used to achieve the same function. I believe that keeping other.js will be more beneficial than deleting this js

**Comment by 422658476** [comment]
I closed this, if you have any questions, please reopen 。
