### ISSUE TITLE
Make it fully Open-Source

### ISSUE THREAD

**Issue by z8512** [422658476/MPV-EASY-Player#43]
And how to build this app?

**Comment by 422658476** [comment]
Sorry, this program was originally made to solve the problem that mpv does not support Chinese paths. Of course, it uses non-source codes that must also be used in other programs. It has become like this because of constant updates. If all are open source, it will affect my other programs. Without those closed source programs, this program would not exist. This is very contradictory, and I have no choice. It's a chicken-and-egg conflict. Although this program is not currently open source, it will always be free and you can use it as much as you like.

**Comment by z8512** [comment]
Can you give instructions how to build it?

**Comment by 422658476** [comment]
Does it make sense for you to ask this question without the source code?

**Comment by z8512** [comment]
Oh sorry
