### ISSUE TITLE
Publish mpv EASY Player in WinGet

### ISSUE THREAD

**Issue by bitsper2nd** [422658476/MPV-EASY-Player#46]
Just as the title says. Can you publish your mpv fork on the [Windows Package Manager](https://github.com/microsoft/winget-cli)? You can install, remove and update programs from the terminal. You can also import and export a list of installed programs. [Get information about the program in the CLI](https://github.com/microsoft/winget-pkgs). In summary, its very convenient way for those of us experienced in the command line, manage software on Windows. Best part, its free. There are paid programs right now being distributed on WinGet like WinRAR, Sublime Text, Listary, PostBox, AdGuard etc..

**Comment by 422658476** [comment]
Using this method to manage software under windows is a complete step backwards, even to the point of [apt-get install] under linux.
If this installation method is good, why are Windows, Mac, and Linux all using the program store to manage software? How many people will use this software installation method in windows? 1? Or 2, why do most people still use the installation package?
The linux program store is the earliest, and the stores under mac and windows are imitators of the linux program store.
Why does linux want a program store?
Because distributions such as ubuntu know that using the command line to install software is not acceptable to most people, even the Synaptic package manager is difficult for ordinary people to use. Do you let users solve dependencies and errors? One line of characters is required to install software. Does the user know the name of the software he needs in apt-get?
I've been using linux for over ten years now and I try to avoid the command line because it's definitely not the future.
One of the development goals of MPV-EASY Player from the beginning is to become a standard portable software. MPV-EASY Player does not actually need to be installed, why should a software that does not need to be installed be added to apt-get under windows?
It is like an appimage under linux, you can download it anywhere on the network, decompress it and use it immediately, you don't need to worry about compatibility, error reporting, etc. After installing a new system, you don't need to worry about the program being lost, and it can run immediately.
Decompression is also the most convenient way to use the software, and updating is also the most convenient. Repeat the download and decompression process, everyone can do it, and no one needs to teach it.
Why put software into a program that recreates outdated wheels under Windows?
Microsoft itself is actually doing this kind of thing in 2022. . . . omg. . Is this to let some people use the operating system to go back to the stone age?
I guess this thing is only useful when managing embedded linux under windows.
What's even more ironic is: writing MPV-EASY Player, using a graphical way to help users easily control mpv, which itself is to let users get rid of the command line.


No problem please close this issue.

**Comment by bitsper2nd** [comment]
I mean its another way to distribute and manage programs on Windows. I believe the use case for this, apart from people that larp in the command line, is for system admins that work with various Windows installations that need specific programs. You can distribute portable software in WinGet now. I mostly use WinGet to update programs on Windows 11. Makes it really easy for me.
