### ISSUE TITLE
HLS m3u8 streams

### ISSUE THREAD

**Issue by trimechee** [422658476/MPV-EASY-Player#53]
Hello, ffmpeg seems to have some problems to decode hls m3u8 streams, but a tool like HLSDL seems to solve these problems, please it will be great if there is support for specific hls streams of some websites by integrating these m3u8 softwares to avoid these bugs, thank you so much ! 

C program to download VoD HLS (.m3u8) files

https://github.com/selsta/hlsdl

m3u8 : Python m3u8 Parser for HTTP Live Streaming (HLS) Transmissions :

https://github.com/globocom/m3u8

[.NET] m3u8 downloader Open source command line m3u8/HLS/dash downloader, supports common AES-128-CBC decryption, multi-threading, custom request headers, etc. Supports Simplified Chinese, Traditional Chinese and English. English Supported.

https://github.com/nilaoda/N_m3u8DL-CLI

[.NET7] Cross-Platform stream downloader for DASH/HLS.

https://github.com/nilaoda/N_m3u8DL-RE

and

https://github.com/HeiSir2014/M3U8-Downloader

https://github.com/Spark-NF/hls-downloader

 " HLSDL appears working much better than ffmpeg in these cases.
Hlsdl is public and the source code available.
The stream plays almost immediately and is stable. No errors or buffering.
Using ffmpeg for the download step gives a very long intial delay and is not very stable.
so I assume that the new crypto+hls RAI flows are badly handled by ffmpeg based players now.

 the video is choppy and unable to buffer enough for a fluid vision. Parole has no problem.

FFmpeg is not good for HLS streams, but I watched a lot of various HLS streams without any problems. The main problem is that FFmpeg downloads all streams (many video sizes at once), so you can watch only HLS stream with single video size"

**Comment by 422658476** [comment]
Sorry, you may need to consult the mpv official for these functions, because mpv easy player is just a front end of mpv, it does not actually process what you said, when mpv easy player plays online video streams, it just passes the video link to mpv.exe, actually mpv.exe handles all downloading, buffering and playing video content

**Comment by 422658476** [comment]
It doesn't matter, I believe the mpv official will give you a more professional explanation. The questions you submit are likely to improve the effect of mpv when playing them.

**Comment by 422658476** [comment]
You describe too many things, and since English is not my native language, I can only briefly answer you.

If you want to see the English version of the changelog, please see:
https://www.softpedia.com/get/Multimedia/Video/Video-Players/MPV-EASY-Player.shtml

https://www.softpedia.com/progChangelog/MPV-EASY-Player-Changelog-258866.html

Softpedia official staff are very friendly and diligent, every time a new version is released they will translate the changelog into English, you can check it here.

Usually mpv handles caching automatically, so you usually don't need to worry about this.

If you want to cache by seconds, open with a text editor:

mpv-easy player\data\mpv-easy-data\rjno1.conf

All settings in mpv.conf have been migrated to this folder.

Please add a line below [ini-rjno1]:

cache-secs=<seconds>

To add more cache-related settings, please check the manual.pdf provided by mpv, most of the settings are compatible with mpv-easy player, and the --cache section has all the instructions you want.

If you want to monitor cache size or download speed while playing online video, just:

Use the menu [Show file information] or [i] or uppercase [i] (permanent display) to view the total cache in the third line.

If you want to check the current download speed, please press [3] above the button [Q] after the file information interface is displayed, and the displayed [speed] is the download speed you want.
Press [1] above [Q] again to switch back to the file information page.

When pressing [3] and not pressing [1] to switch back to the file information page, then next time you use the menu [Show file information] or [i] or capitalized [i], the page of [speed] will be displayed directly.

mpv-easy player is a local player, it will not pay attention to the problems caused by playing online videos, because online videos are usually difficult to obtain the correct address, and debugging will also be very difficult.

In fact, online videos are still recommended to be downloaded and played.
