### ISSUE TITLE
[How] I want deleted manually items from history + [R - Feature]

### ISSUE THREAD

**Issue by Milor123** [422658476/MPV-EASY-Player#58]
Hi Guys, thank you very much for add the 20 items to the history. I am very happy with it. 

I would know how can i deleted some items from history, for example items that accidentally are repeated or items of series that I've finished, And I want do it for keep the correct track of series that i want see

![image](https://user-images.githubusercontent.com/14153649/204144305-66995a72-0223-48dd-a393-7be101a86310.png)

In addition to this, I would like to know if it is possible to add more than 20 items to the history, for example 30 or 40?

A nice feature that could be added would be "right click delete history item" or a special menu where you can view the entire history and allow you to delete multiple items and even change the order.

Thank you very much for this great project, I love it. !!!

**Comment by 422658476** [comment]
The historical record comes from mpv itself, how mpv generates these lists, mpv-easy player will only generate according to this list.

In terms of your usage habits, what you need is one or more playlists to manage videos instead of history. Please don't use history to replace all functions of playlists.

It is recommended to add all the videos that need to be played recently to one or more playlist files and store them in the specified folder. The various editing and sorting functions provided by the advanced playlist are all the functions you need.

**Comment by Milor123** [comment]
> The historical record comes from mpv itself, how mpv generates these lists, mpv-easy player will only generate according to this list.
> 
> In terms of your usage habits, what you need is one or more playlists to manage videos instead of history. Please don't use history to replace all functions of playlists.
> 
> It is recommended to add all the videos that need to be played recently to one or more playlist files and store them in the specified folder. The various editing and sorting functions provided by the advanced playlist are all the functions you need.

Thank you very much, I am not sure about understand you. I so so understand the algorithm the behavior. 

How can I open to  the last chapter seen from (MPV) in a folder [folder/video5.mpv], without use the history items? Is it a feature? Maybe i dont understand like works the playlist, but according to me, the MPV loads a playlist when i try add some video of a folder with many videos.  Thanks for help me bro

**Comment by 422658476** [comment]
I thought about it again, actually all you want is a list of unwatched videos, and you want to sort them yourself, which is why you want to do these unreasonable operations on history.

In fact, it is impossible for the playlist to solve this problem. The playlist is designed to play serials. It sorts all videos according to the video file name, and when the history is turned on, playing the playlist file will ignore the playback progress (of course, in the settings Jump to playback progress can be turned on), and it will start playing from the first video every time without deleting the finished files in the playlist.

Regardless of whether to ignore the playback progress or start playing from the first video, using a playlist to manage a list of unwatched videos is very labor-intensive, because it needs to delete, add, and manage the order.

If you want to solve the problem you encountered, please optimize the folder structure of the file explorer,

For example, put all unwatched videos into this folder.

D:/unwatched video

Among them, the videos that have been watched are manually transferred to the watched subfolder:

D:/unwatched video/watched

In this way, the unwatched video folder is the list you need, and you can also use the sorting function of the file explorer to sort these video files without worrying about the number of videos.

This is also the easiest and most feasible way.
