### ISSUE TITLE
Add the ability to load external subtitle or audio files

### ISSUE THREAD

**Issue by xKeiro** [422658476/MPV-EASY-Player#6]
As far as I can see, there's no option to manually select an external subtitle/audio file if the program doesn't detect it by default. 

(Example case: I have a video file with low quality audio and high quality audio files of that video in a different folder, it would be great if I could manually add them to the playback without the need to moving them to the same folder and naming the audio files the same as the video file)

**Comment by 422658476** [comment]
By default, mpv will automatically detect external subtitle files. As you said, you only need to put subtitles in the same path as the video file, and the names are the same.

You are talking about a video file, 2 different audio files, and you want to play one of the audio files when you want to play the video file.
If you often need this, the way you use it is very cumbersome and unnecessary, and most people will not encounter it. If you want to solve this problem conveniently, you don't actually rely on the player, but you need to rely on the video. Converters, such as the free and versatile XMedia Recode, you only need to add these 2 audio files as audio files, and combine them into one mkv file. Both video and audio use [copy] when converting, so that the picture quality and sound quality will not be damaged, that is, just combine video and audio. And the whole process is very fast, because it does not involve the real conversion, if it is a movie, then according to the performance of your hard disk and cpu, about 5 minutes. Click to switch the track during playback, and you don't need to add it again next time.
