### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [422658476/MPV-EASY-Player#91]
1-Add` an option to show the progress bar while in full screen 

2-Add an option to show a osd message after opening the next file in playlist 
like : " 12/20  xxxE08.mp4"

3-Add thumbfast script support

**Comment by 422658476** [comment]
1. This setting will not be added. If you want to monitor the progress in full screen, please use shift+o, which is the shortcut key capital o, to display the progress in osd.
2.  Please check the user manual of mpv, please add and modify the 

osd-playing-msg='${filename}' 

setting to achieve the effect you want. 
3. Please manually add the script to use in mpv native gui. This function will not be added in mpv-easy borderless mode due to performance issues. Please turn on the drag progress bar to jump to the real-time progress to get a similar effect.

**Comment by 422658476** [comment]
Settings-osc-The only option related to dragging the progress bar
