### ISSUE TITLE
osd-bar: can we customize the chapter marker 

### ISSUE THREAD

**Issue by VimWei** [422658476/MPV-EASY-Player#95]
By default, the upper edge of the chapter marker is an inverted triangle, while the lower edge is a regular triangle. 

![image](https://github.com/user-attachments/assets/7ae88863-efdd-4127-806f-d8e9a2c0a816)

However, due to the narrow height of the OSD bar (0.4), the two chapter markers overlap, creating a cluttered appearance.

![image](https://github.com/user-attachments/assets/6ff2d7af-fc41-4a11-984f-65d1f85f975a)

Is it possible to customize the style of the chapter marker? For example, could we use a slimmer vertical bar or  a gap, similar to the playback bar on YouTube?

![image](https://github.com/user-attachments/assets/55eabc96-6aa0-4919-9a36-f197ba7472b9)

**Comment by VimWei** [comment]
By the way, if I want a minimal configuration for osd-bar.lua, is the following setup correct?

```
osd-bar-w=100
osd-bar-h=0.4
osd-bar-align-y=1
osd-bar-border-size=0
osd-color=1.0/1.0/1.0/0.66
osd-back-color=1.0/1.0/1.0/0.22
osd-border-size=1
osd-border-color=0.0/0.0/0.0/0.3
osd-shadow-offset=6
osd-border-style=background-box
```

**Comment by 422658476** [comment]
You need to check the manual to adjust it yourself or consult the developer of mpv.

mpv-easy player did not modify any code of osd-bar and main progress bar, but only modified the settings.

And we cannot discuss the style of osd-bar and main progress bar at the same time. The two are generated by completely different codes. The style of osd-bar in mpv-easy player is similar to the style of main progress bar in mpv by modifying the settings. The original osd-bar is in the middle of the screen and the style is completely different.

If you discuss the adjusted osd-bar and main progress bar styles with the mpv developer, it will become more confusing. Usually, these can only be adjusted by yourself.

Tips:

The style of osd-bar and its chapter markers may be created by this file, but it is not certain:
console.lua
You need to ask the code contributor who generates the osd-bar style or study it yourself. If osd-bar is created by a lua file, such as console.lua, then you only need to modify the code to change the style of the chapter markers, and put the modified console.lua file in the script folder to overwrite the built-in mpv, but the main progress bar style is responsible for osc.lua, you need to modify osc.lua to change the main progress bar style.

If you think the current osd-bar style is not good-looking, you can try to adjust the settings, such as the osd-bar height. Adjusting to a higher height can avoid the two arrows covering each other.

In theory, it is impossible to have chapters like youtube, unless mpv greatly improves the progress bar style.

Because the main progress bar in the official osc.lua of mpv needs to render the buffered part here when playing online videos, which is different from the progress bar of youtube, which will conflict with the chapter effect you want and cause confusion.

What is [minimal configuration]? I don't understand. You can modify all osd-bar settings in rjno1.conf yourself or add additional settings to it according to the mpv manual.

**Comment by VimWei** [comment]
Thanks!

**Comment by VimWei** [comment]
Fixed: https://github.com/mpv-player/mpv/pull/15183

**Comment by 422658476** [comment]
MPV official response is too fast
